import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import ViewCanvas from "./components/ViewCanvas";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const alpino = localFont({
  src: "../public/fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={alpino.variable}>
      <head>
        <link rel="icon" href="/logo.svg" sizes="any" />
      </head>
      <body className="overflow-x-hidden bg-yellow-300">
        <Header />
        {children}
        <ViewCanvas />
      </body>
    </html>
  );
}
